version: '3'
services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=qwer1234
    command: --authentication-policy=mysql_native_password
    networks:
      - mynetwork
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  zmq-server:
    image: zmq
    build: ../PPL_Cmake_Zmq_Server
    container_name: zmq-server
    ports:
      - 7777:7777
    depends_on:
      - mysql-server
    networks:
      - mynetwork

  http-server:
    image: http
    build: ../PPL_Cmake_Http_Server
    container_name: http-server
    ports:
      - 10000:10000
    depends_on:
      - zmq-server
    networks:
      - mynetwork

networks:
  mynetwork:
